# Generated by Django 4.0.1 on 2022-02-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('text', models.CharField(max_length=500, verbose_name='Описание страницы')),
                ('map', models.CharField(blank=True, help_text='frame карты', max_length=500, verbose_name='Ссылка на карту')),
                ('phone', models.CharField(help_text='Номер без +7', max_length=10, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook', models.CharField(blank=True, max_length=60, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=60, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=60, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
