# Generated by Django 4.0.1 on 2022-02-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(default=1, max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
