# Generated by Django 4.0.1 on 2022-05-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_contact', '0002_contact_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
