# Generated by Django 4.0.1 on 2022-08-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_contact', '0003_formcontactpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formcontactpage',
            options={'verbose_name': 'Заявки с формы на странице Контакты', 'verbose_name_plural': 'Заявки с формы на странице Контакты'},
        ),
        migrations.AlterField(
            model_name='formcontactpage',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Enail'),
        ),
        migrations.AlterField(
            model_name='formcontactpage',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='formcontactpage',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='formcontactpage',
            name='subject',
            field=models.CharField(blank='True', max_length=100, verbose_name='Тема обращения'),
        ),
    ]
