# Generated by Django 4.0.1 on 2022-01-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название галереи')),
            ],
            options={
                'verbose_name': 'Галерея объекта',
                'verbose_name_plural': 'Галереи объекта',
            },
        ),
        migrations.CreateModel(
            name='PropertyOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название опции')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('price', models.PositiveIntegerField(help_text='Цена в ₽', verbose_name='Цена объекта')),
                ('descripton', models.TextField(verbose_name='Описание объекта')),
                ('property_id', models.PositiveSmallIntegerField(verbose_name='ID объекта')),
                ('location', models.CharField(max_length=150, verbose_name='Расположение')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Тип объекта')),
                ('area', models.PositiveSmallIntegerField(blank=True, verbose_name='Площадь')),
                ('room', models.PositiveSmallIntegerField(blank=True, verbose_name='Кол-во комнат')),
                ('baths', models.PositiveSmallIntegerField(blank=True, verbose_name='Кол-во ванных комнат')),
                ('garage', models.PositiveSmallIntegerField(blank=True, verbose_name='Кол-во гаражей')),
                ('photo_preview', models.ImageField(null=True, upload_to='property_preview/', verbose_name='Фото для списка')),
                ('video', models.URLField(max_length=150, null=True, verbose_name='Ссылка на видео объекта')),
                ('plans', models.ImageField(null=True, upload_to='property_plans/', verbose_name='План проекта')),
                ('cordinate_x', models.FloatField(verbose_name='Координаты широта')),
                ('cordinate_y', models.FloatField(verbose_name='Координаты долгота')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Публикация')),
                ('options', models.ManyToManyField(to='eastate_property.PropertyOptions', verbose_name='Опиции')),
                ('photo_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eastate_property.propertygallery', verbose_name='Галерея объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
