# Generated by Django 4.0.1 on 2022-01-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertygallery',
            name='image',
            field=models.ImageField(default=1, upload_to='property_photos/', verbose_name='Фото объекта'),
            preserve_default=False,
        ),
    ]
