# Generated by Django 4.0.1 on 2022-01-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0004_alter_propertytype_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
