# Generated by Django 4.0.1 on 2022-01-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0005_alter_propertytype_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytype',
            name='url',
        ),
    ]
