# Generated by Django 4.0.1 on 2022-01-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0006_remove_propertytype_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
    ]
