# Generated by Django 4.0.1 on 2022-01-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0007_remove_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eastate_property.propertytype', verbose_name='Галерея объекта'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='url',
            field=models.SlugField(default=1, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
