# Generated by Django 4.0.1 on 2022-01-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0008_property_type_propertytype_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во гаражей'),
        ),
        migrations.AlterField(
            model_name='property',
            name='options',
            field=models.ManyToManyField(related_name='options_list', to='eastate_property.PropertyOptions', verbose_name='Опиции'),
        ),
        migrations.AlterField(
            model_name='property',
            name='plans',
            field=models.ImageField(blank=True, upload_to='property_plans/', verbose_name='План проекта'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eastate_property.propertytype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.URLField(blank=True, max_length=150, verbose_name='Ссылка на видео объекта'),
        ),
    ]
