# Generated by Django 4.0.1 on 2022-01-23 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agents', '0001_initial'),
        ('eastate_property', '0009_alter_property_garage_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estate_agents.agent', verbose_name='Агент'),
        ),
    ]
