# Generated by Django 4.0.1 on 2022-01-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agents', '0001_initial'),
        ('eastate_property', '0010_property_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_property', to='estate_agents.agent', verbose_name='Агент'),
        ),
    ]
