# Generated by Django 4.0.1 on 2022-01-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0011_alter_property_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='cordinate_x',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cordinate_y',
        ),
        migrations.AddField(
            model_name='property',
            name='map',
            field=models.CharField(blank=True, help_text='Сформированная ссылка на карту с любого сервиса, через кнопку «Поделиться»', max_length=500, verbose_name='Ссылка на карту'),
        ),
    ]
