# Generated by Django 4.0.1 on 2022-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0012_remove_property_cordinate_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertygallery',
            name='image',
        ),
        migrations.AddField(
            model_name='propertygallery',
            name='image1',
            field=models.ImageField(blank=True, help_text='Певрое фото обязательное, осатльные нет', upload_to='property_photos/', verbose_name='Фото объекта 1'),
        ),
        migrations.AddField(
            model_name='propertygallery',
            name='image2',
            field=models.ImageField(blank=True, upload_to='property_photos/', verbose_name='Фото объекта 2'),
        ),
        migrations.AddField(
            model_name='propertygallery',
            name='image3',
            field=models.ImageField(blank=True, upload_to='property_photos/', verbose_name='Фото объекта 3'),
        ),
        migrations.AddField(
            model_name='propertygallery',
            name='image4',
            field=models.ImageField(blank=True, upload_to='property_photos/', verbose_name='Фото объекта 4'),
        ),
        migrations.AddField(
            model_name='propertygallery',
            name='image5',
            field=models.ImageField(blank=True, upload_to='property_photos/', verbose_name='Фото объекта 5'),
        ),
        migrations.AlterField(
            model_name='property',
            name='map',
            field=models.CharField(blank=True, help_text='frame карты', max_length=500, verbose_name='Ссылка на карту'),
        ),
    ]
