# Generated by Django 4.0.1 on 2022-08-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0015_property_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_slider',
            field=models.BooleanField(default=False, verbose_name='Отобажать в слайдере'),
        ),
    ]
