# Generated by Django 4.0.1 on 2022-01-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя Агента')),
                ('description', models.TextField(help_text='Описание на 300 символов', max_length=300, verbose_name='Описание агента')),
                ('photo', models.ImageField(upload_to='agents/', verbose_name='Фото агента')),
                ('phone', models.CharField(help_text='Номер без +7', max_length=10, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook', models.CharField(blank=True, max_length=60, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=60, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=60, verbose_name='Instagram')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
        ),
    ]
