# Generated by Django 4.0.1 on 2022-01-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0011_alter_property_agent'),
        ('estate_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='property_agent',
            field=models.ManyToManyField(related_name='property_agent', to='eastate_property.Property', verbose_name='Обеъекты агента'),
        ),
    ]
