# Generated by Django 4.0.1 on 2022-04-27 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={},
        ),
        migrations.AlterField(
            model_name='benefits',
            name='benefits',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='benefits_id', to='estate_index.index'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='review_id', to='estate_index.index'),
        ),
    ]
