# Generated by Django 4.0.1 on 2022-04-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_blog', '0016_alter_category_url'),
        ('estate_index', '0002_alter_benefits_options_alter_benefits_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='index_blog',
            field=models.ManyToManyField(related_name='blog_index', to='estate_blog.Blog', verbose_name='Последние публикации'),
        ),
    ]
