# Generated by Django 4.0.1 on 2022-04-27 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_index', '0003_index_index_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='index_blog',
        ),
    ]
