# Generated by Django 4.0.1 on 2022-04-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agents', '0002_agent_property_agent'),
        ('estate_index', '0004_remove_index_index_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='index_agents',
            field=models.ManyToManyField(related_name='index_agents', to='estate_agents.Agent', verbose_name='Лушие агенты'),
        ),
    ]
