# Generated by Django 4.0.1 on 2022-04-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eastate_property', '0014_alter_propertygallery_image1'),
        ('estate_index', '0005_alter_index_index_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='index_property',
            field=models.ManyToManyField(related_name='index_property', to='eastate_property.Property', verbose_name='Новые объекты'),
        ),
    ]
