# Generated by Django 4.0.1 on 2022-04-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_index', '0006_index_index_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='facebook',
            field=models.CharField(blank=True, max_length=60, verbose_name='Facebook в подвале'),
        ),
        migrations.AddField(
            model_name='index',
            name='instagram',
            field=models.CharField(blank=True, max_length=60, verbose_name='Instagram в подвале'),
        ),
        migrations.AddField(
            model_name='index',
            name='twitter',
            field=models.CharField(blank=True, max_length=60, verbose_name='Twitter в подвале'),
        ),
    ]
