# Generated by Django 4.0.1 on 2022-08-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_index', '0008_remove_index_index_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='index_property',
        ),
    ]
