# Generated by Django 4.0.1 on 2022-08-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_index', '0009_remove_index_index_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='slider',
        ),
    ]
