# Generated by Django 4.0.1 on 2022-02-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate_agents', '0002_agent_property_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('banner_photo', models.ImageField(upload_to='about/', verbose_name='Баннер страницы')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Заголовок баннера')),
                ('banner_descr', models.CharField(max_length=100, verbose_name='Описание баннера')),
                ('page_photo', models.ImageField(upload_to='about/', verbose_name='Фото страницы')),
                ('page_title', models.CharField(max_length=100, verbose_name='Заголовок страницы')),
                ('page_descr', models.TextField(verbose_name='Текст страницы')),
                ('about_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_about', to='estate_agents.agent', verbose_name='Агент')),
            ],
        ),
    ]
