# Generated by Django 4.0.1 on 2022-02-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agents', '0002_agent_property_agent'),
        ('estate_about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О компании', 'verbose_name_plural': 'О компании'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_agent',
        ),
        migrations.AddField(
            model_name='about',
            name='about_agent',
            field=models.ManyToManyField(related_name='agent_about', to='estate_agents.Agent', verbose_name='Агент'),
        ),
    ]
