# Generated by Django 4.0.1 on 2022-02-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_about', '0002_alter_about_options_remove_about_about_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_agent',
            new_name='about',
        ),
    ]
