# Generated by Django 4.0.1 on 2022-02-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_about', '0003_rename_about_agent_about_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='agent_about',
        ),
    ]
