# Generated by Django 4.0.1 on 2022-04-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agents', '0002_agent_property_agent'),
        ('estate_about', '0004_rename_about_about_agent_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='agent_about',
            field=models.ManyToManyField(related_name='agent_about', to='estate_agents.Agent', verbose_name='Агенты'),
        ),
    ]
