# Generated by Django 4.0.1 on 2022-01-19 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название категории')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название статьи')),
                ('autor', models.CharField(max_length=60, verbose_name='Автор статьи')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('image_preview', models.ImageField(upload_to='blog_preview/', verbose_name='Превью изображения')),
                ('image_main', models.ImageField(upload_to='blog_main/', verbose_name='Основное изображение')),
                ('text_preview', models.TextField(verbose_name='Вводный текст')),
                ('text_main', models.TextField(verbose_name='Текст статьи')),
                ('text_quote', models.TextField(verbose_name='Цитата')),
                ('quote_autor', models.CharField(max_length=60, verbose_name='Автор цитаты')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Публикация')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estate_blog.category', verbose_name='Категория статьи')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
    ]
