# Generated by Django 4.0.1 on 2022-01-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_blog', '0003_alter_blog_quote_autor_alter_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='quote_autor',
            field=models.CharField(blank=True, max_length=60, verbose_name='Автор цитаты'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
