# Generated by Django 4.0.1 on 2022-01-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_blog', '0004_alter_blog_quote_autor_alter_blog_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
