# Generated by Django 4.0.1 on 2022-01-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_blog', '0010_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
