# Generated by Django 4.0.1 on 2022-01-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_blog', '0011_remove_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(max_length=130, null=True),
        ),
    ]
