# Generated by Django 4.0.1 on 2022-01-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_blog', '0012_category_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='url_cat',
        ),
    ]
