# Generated by Django 4.0.1 on 2022-05-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_blog', '0016_alter_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seo_descr',
            field=models.CharField(default=1, max_length=150, verbose_name='SEO описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_title',
            field=models.CharField(default=1, max_length=70, verbose_name='SEO заголовок'),
            preserve_default=False,
        ),
    ]
